// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MoreTweaksToStockAndOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreTweaksToStockAndOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201410282222039_MoreTweaksToStockAndOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
